### ISSUE TITLE
Recently installed figmiro and it's not working

### ISSUE THREAD

**Issue by flatwh8** [RedMadRobot/figmiro-plugin#10]
Recently installed both Figma and Figmiro, but for some reason my frames/artboards aren't exporting to designated miro. However, if I did a test by d/l a free Figma file and copied and pasted a board from that into my project, it seems to work, that copied board works when exporting to Miro. What do I need to do to my artboards?

**Comment by flatwh8** [comment]
Ah... I did another test, and it seems it doesn't like my file naming on one of the artboards.

**Comment by ilyakrupnov** [comment]
Fixed
