### ISSUE TITLE
can't see other boards, just the ones I created

### ISSUE THREAD

**Issue by demoklion** [RedMadRobot/figmiro-plugin#11]
Hey, thanks for this plugin. If it works how it should, it will save me a lot of pain.

So my issue is, I see only the boards I have created, not the ones I've been invited to. 

In Figma I go to Plugins -> Figmiro, plugin opens and logs me in with miro credentials. In the plugin, in the Sync tab, I see only (3) my boards, but not boards I've been invited to (10?).

Thanks, lemme know how I can provide more info.

**Comment by ilyakrupnov** [comment]
We've just update plugin. It should be fixed

**Comment by demoklion** [comment]
Yes it is ❤️

pá 6. 8. 2021 v 12:28 odesílatel Ilya Michailovich Krupnov <
***@***.***> napsal:
