### ISSUE TITLE
Login to plugin under Single Sign On (SSO)

### ISSUE THREAD

**Issue by danielgost83** [RedMadRobot/figmiro-plugin#13]
Hi, thanks for creating this plugin - it is so helpful to be able to sync between Figma<>Miro.

I'm using a Miro corporate account. Since I'm using Single Sign On (SSO), I don't seem to be able to login to the plugin. **Quick question:** Is there any way I can login using an SSO account? If not, any plans to make it available in the near future?

Many thanks!

**Comment by thomaskrammer** [comment]
Hi @danielgost83 

I experienced the same issue and fixed it with that workaround:

1. Logout at miro.com or open miro.com in a private browser tab
2. Click "Login"
3. Click "Forgot password?" on the login form
![image](https://user-images.githubusercontent.com/3432361/83739010-506d6900-a655-11ea-8666-429c2d6d7094.png)
4. Wait for the email with the password reset link
5. Define a password for your Miro account
6. You can now use your SSO email address and the password (defined in step 5) to log in in Figmiro

Hope that helps!

**Comment by loized** [comment]
Hi Thomas, thanks for you tip but in my company it doesn't allow us to sign in without SSO even in private mode. 

The plug in is super useful and would be great if we could log in with SSO too if possible. :(

**Comment by fwg001** [comment]
This workaround doesn't work for me either. I would love to use Figmiro but need to use SSO login support.

**Comment by jklein-bloop** [comment]
I have the same problem, and am unable to use this plug-in without SSO login support.

**Comment by Maskerad** [comment]
Workaround doesn't work for us either - please prioritize some solution here :D

**Comment by ilyakrupnov** [comment]
We've provided this feature
