### ISSUE TITLE
Посторонние символы в именах

### ISSUE THREAD

**Issue by karasov** [RedMadRobot/figmiro-plugin#19]
Ребят, если будет возможность, уберите, пожалуйста, добавление лишних символов в имена картинок. Речь о том, что на досках картинки выгружаются с именами примерно такого формата: `*file_name*__ce7093ae2db54c2e8185c042a9dfd3f8__` и это доставляет определённые неудобства при работе с доской.

**Comment by ilyakrupnov** [comment]
Сейчас это поправили, есть еще некоторые проблемы с синхронизацией, будем исправлять
