### ISSUE TITLE
2nd Miro account won't log in

### ISSUE THREAD

**Issue by melamour** [RedMadRobot/figmiro-plugin#21]
I used Figmiro successfully with my first Miro account.
When I needed to switch Miro accounts, I am unable to log into the second one.
I changed passwords, uninstalled/reinstalled plugin and now neither account logs in.
I get this message: 
![image](https://user-images.githubusercontent.com/77702443/105103650-c5b37000-5a65-11eb-90df-41462d4cb30c.png)
Really miss using this plugin!!
Thanks for your help!

**Comment by ilyakrupnov** [comment]
I've fixed that
