### ISSUE TITLE
Syncing Miro Boards issue

### ISSUE THREAD

**Issue by mostafaadel174** [RedMadRobot/figmiro-plugin#24]
I'm trying to choose the board that I want to sync the screen with and none of them appears. I tried to logout and log back in and didn't help.

![image](https://user-images.githubusercontent.com/6493997/106380335-0a76c980-63cb-11eb-9695-2d0f4b148911.png)
![image](https://user-images.githubusercontent.com/6493997/106380400-66415280-63cb-11eb-84b1-b9df75dc411d.png)

**Comment by cloud9209** [comment]
I'm having this issue too

**Comment by psanden** [comment]
Having this issue as well. Tired to logout and then can't log in again and get a Network error
![image](https://user-images.githubusercontent.com/1526842/106399363-3dbd6500-646c-11eb-9f48-8743b18c00c3.png)

Restarting everything, Figma, Miro and COmputer does not help

**Comment by Puranjai256** [comment]
I'm having the exact same issue for the last 3 days

**Comment by lukasimrich** [comment]
+1 the same issue here

**Comment by mobester** [comment]
+1 please, fix it! (

**Comment by nielsemann** [comment]
+1 please fix 😀

**Comment by JuliaAg** [comment]
+1 пожалуйста исправьте)

**Comment by mobester** [comment]
Да, ребят, поправьте плиз! На самом деле плагин просто супер. И особенно остро понимаешь это когда он второй день не работает и приходится вручную синхронизировать макеты в фигме с флоу в миро через png..

**Comment by Cooldaa** [comment]
+1

**Comment by pzlgrv** [comment]
+1

**Comment by kamihula** [comment]
+1 ☹️

**Comment by jannell** [comment]
Same issue. Tried uninstalling and reinstalling too ☹️

**Comment by camihuerta** [comment]
I'm having the same issue from yesterday :( Please help us! thank you!!

**Comment by ilyakrupnov** [comment]
Now it's fixed!)
Maybe in april it could happen again, but for now it's ok!

**Comment by cloud9209** [comment]
Thank you very much @ilyakrupnov !! 👍👍
