### ISSUE TITLE
Miro boards not showing up in select to sync dropdown

### ISSUE THREAD

**Issue by jannell** [RedMadRobot/figmiro-plugin#31]
Currently logged in, selected which screens to sync on Figma, opened up Figmiro to select which Miro boards to sync to and the dropdown states "No such board."

**Comment by puranjai-8** [comment]
Same here, boards were not showing up so I decided to log out and now I cannot log in as it's showing network error. I tried uninstalling , changing Miro password but nothing is working

**Comment by mobester** [comment]
Тоже самое.. no such board, почините, пожалуйста..

**Comment by Emrescue** [comment]
I have this problem too. Please help to fix it.

**Comment by linastrid** [comment]
same here!

**Comment by sarahwr** [comment]
Same issue here - and our whole team is affected. Please help with a solution!

**Comment by marisnaylor** [comment]
So does this plugin just not work anymore? Need to know so I can figure out another solution.

**Comment by ValeriiMakhniuk** [comment]
It seems the problem is that server host's SSL certificate has expired
**Solution:**
1. Deploy the [server](https://github.com/RedMadRobot/figmiro-server) on your own
2. Locally build the plugin and change the host url(hosted server) like shown on [video](https://github.com/RedMadRobot/figmiro-plugin/blob/master/images/how-to-install.gif)
3. Add plugin in Figma via development tab like shown on [video](https://github.com/RedMadRobot/figmiro-plugin/blob/master/images/how-to-install.gif)

**Comment by sarahwr** [comment]
> It seems the problem is that server host's SSL certificate has expired
> **Solution:**
> 
> 1. Deploy the [server](https://github.com/RedMadRobot/figmiro-server) on your own
> 2. Locally build the plugin and change the host url(hosted server) like shown [on](https://imgur.com/a/FB5fHrA)
> 3. Add plugin in Figma via development tab like shown on [video](https://github.com/RedMadRobot/figmiro-plugin/blob/master/images/how-to-install.gif)

@ValeriiMakhniuk thank you for this, but is installing it on our own server the only option?

**Comment by ValeriiMakhniuk** [comment]
> > It seems the problem is that server host's SSL certificate has expired
> > **Solution:**
> > 
> > 1. Deploy the [server](https://github.com/RedMadRobot/figmiro-server) on your own
> > 2. Locally build the plugin and change the host url(hosted server) like shown [on](https://imgur.com/a/FB5fHrA)
> > 3. Add plugin in Figma via development tab like shown on [video](https://github.com/RedMadRobot/figmiro-plugin/blob/master/images/how-to-install.gif)
> 
> @ValeriiMakhniuk thank you for this, but is installing it on our own server the only option?

@sarahwr I think - yes. For my team i publish it on [heroku](https://www.heroku.com/home) with free plan

**Comment by ilyakrupnov** [comment]
It's working now
