### ISSUE TITLE
Error: please reduce the size of the image...

### ISSUE THREAD

**Issue by disraelyan1** [RedMadRobot/figmiro-plugin#40]
<img width="308" alt="Screen Shot 2021-08-09 at 11 21 01 AM" src="https://user-images.githubusercontent.com/88452582/128902047-bd4447aa-9f35-47d1-bd76-9e3f7c8d5d5a.png">
I get an error if the image is too big? This never happened before even with larger images. 

What's going on with this plugin? It's gone completely to shit!

**Comment by ilyakrupnov** [comment]
We just connected to the new Miro API, and it has its limit on image uploading (1.5mb) maybe later it would be more.
