### ISSUE TITLE
Figma frame syncs to Miro board but places frame below other content on board

### ISSUE THREAD

**Issue by AndrewCranston** [RedMadRobot/figmiro-plugin#42]
The position of the synced frame keeps on being "reset" to the same spot at the end of the board below all other Miro frames and content. I have to manually go back each time and move the Figma frame object back into position.

The position of the Figma frames stay relative to each other but are put in the wrong place in Miro board.

I would like to have the Figma frame placed on the Miro board and it doesn't matter that I move it to another place on the board, the frame object should sync with Figma automatically.

![image](https://user-images.githubusercontent.com/1695020/138441470-bccb87f5-028c-4c85-bea2-a2d22c88b465.png)

![image](https://user-images.githubusercontent.com/1695020/138441534-f5047f75-9784-426b-92a5-5533c639b89d.png)

**Comment by ilyakrupnov** [comment]
v.1.6.0 changelog:
We are glad to introduce you to a new version of Figmiro!
Now frames export works very similarly to the Sketch-to-Miro plugin, as it was at the beginning of the Figmiro plugin.
 • Frames export made in a similar way as it was at the beginning of Figmiro plugin.
 • Fixed a few bugs.
