### ISSUE TITLE
Respect position on sync

### ISSUE THREAD

**Issue by AngyBrooks** [RedMadRobot/figmiro-plugin#44]
Frame that is synced from Figma to Miro should maintain its size and position in Miro.

**Comment by movie4** [comment]
@ilyakrupnov — what are planning release dates? 
Thanks

**Comment by ilyakrupnov** [comment]
@movie4 Hello, we'll try to do the release this week

**Comment by ilyakrupnov** [comment]
v.1.6.0 changelog:
We are glad to introduce you to a new version of Figmiro!
Now frames export works very similarly to the Sketch-to-Miro plugin, as it was at the beginning of the Figmiro plugin.
 • Frames export made in a similar way as it was at the beginning of Figmiro plugin.
 • Fixed a few bugs.
