### ISSUE TITLE
Unable to log in — OAuth error: "Failed to obtain access token"

### ISSUE THREAD

**Issue by lachlansun** [RedMadRobot/figmiro-plugin#45]
Just ran into an issue whereby I'm unable to log in to Miro in the figmiro plugin due to auth error:
`{"name":"InternalOAuthError","message":"Failed to obtain access token","oauthError":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api.miro.com"}}`

**Comment by ux-dan** [comment]
Also having this same issue as of this morning
{"name":"InternalOAuthError","message":"Failed to obtain access token","oauthError":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api.miro.com"}}

**Comment by phuxen** [comment]
I'm running into this issue also. Was logged out of the plugin and when logging in /reinstalling again I'm presented with this error.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/660858/142336837-35380538-065c-4e43-bd52-61ff6484f199.png">

`{"name":"InternalOAuthError","message":"Failed to obtain access token","oauthError":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api.miro.com"}}`

**Comment by Puranjai256** [comment]
Getting the same issue here

**Comment by mohammedwazier** [comment]
I get this same issue 
![image](https://user-images.githubusercontent.com/5354070/142376195-6c923141-6e64-4e4d-a852-29377398c9fc.png)

**Comment by ilyakrupnov** [comment]
We have fixed it just now:)
