### ISSUE TITLE
Use OAuth instead of requiring login/password

### ISSUE THREAD

**Issue by Subcide** [RedMadRobot/figmiro-plugin#5]
Entering login credentials into a plugin like this feels really insecure.  Please use an API token or OAuth if possible in future.  This should allow use of SSO or google account login with Miro too. Thanks!

**Comment by ilyakrupnov** [comment]
@Subcide Unfortunately, OAuth doesn't allow in iframe, as plugin works in iframe, due to to browser security policies (to prevent clickjacking attacks). So this is not possible:(
