### ISSUE TITLE
Unable to log-in in Miro

### ISSUE THREAD

**Issue by brightnewbright** [RedMadRobot/figmiro-plugin#7]
Thanks for building much needed Figma-Miro bridge!
I installed the plugin yesterday and I've been trying to make it work, but still can't log-in. Triple-checked the password and that's not it. Tried with two different accounts - it doesn't work. Also re-installed the plugin. 
I type in my credentials, no error message and it takes me to main tab, no boards available from the dropdown, then I go back to login tab and see the Authorization failed error message. Both in browser and in-app. Thanks!

**Comment by ilyakrupnov** [comment]
@brightnewbright Hello, thank you for your feedback. We'll try to fix it as soon as possible. Maybe within a week

**Comment by shpthn** [comment]
Hello! 
I have the same problem: I can't log in.

**Comment by thomaskrammer** [comment]
See my comment here for a workaround: https://github.com/RedMadRobot/figmiro-plugin/issues/13#issuecomment-638731144

**Comment by dschultheiss** [comment]
Is this plugin still under development? Is there any support? That Login issue is like 6 months old now. Still not working.

**Comment by sisleyroche** [comment]
Still not working

**Comment by jennxgregory** [comment]
I am experiencing this issue too.

**Comment by ilyakrupnov** [comment]
Fixed
