### ISSUE TITLE
Plugin does not load anymore...

### ISSUE THREAD

**Issue by edwardbattistini** [RedMadRobot/figmiro-plugin#8]
I'm trying to use figmiro but the plugin those not load anymore...

**Comment by boennelykke** [comment]
Same here - says "server error"

**Comment by ilyakrupnov** [comment]
@edwardbattistini @boennelykke Hello! Please provide for us exact steps to reproduce and fix this bug.

**Comment by boennelykke** [comment]
It actually works now - I think it could be because of too big a graphic?

**Comment by ilyakrupnov** [comment]
@boennelykke Yes, probably this can be a reason. There is data limit of 50mb per sync. I'll try to explicitly notify users about this instead of abstract "Server error" exception. Thank you for your feedback!

**Comment by edwardbattistini** [comment]
sorry about my unclear message. I click the plugin but nothing happens...

**Comment by edwardbattistini** [comment]
actually the plugin works on browser but not on the desktop app and few other plugin as well. I think it a figma bug

**Comment by boennelykke** [comment]
Ah I see … maybe the way the desktop app is made?

**Comment by NovaDashka** [comment]
Hi, I use the plugin Figmiro, and all of the screens are loaded from Figma to Miro, but few of them are copied all the time and plugin gives the error "Server error"

**Comment by edwardbattistini** [comment]
It seems that the plugin is working as expected in the desktop mac app. 

@NovaDashka If you are loading a lot of screens I would try to select the option to send `all artboard on the page`  also you should open a separate issue.

**Comment by sebastianv2112** [comment]
Since April 

> It seems that the plugin is working as expected in the desktop mac app.
> 
> @NovaDashka If you are loading a lot of screens I would try to select the option to send `all artboard on the page` also you should open a separate issue.

Not work, at all
